config/routes.rb
Rails.application.routes.draw do
	root "pages#index", via: :get

	scope "/dashboard", module: 'admin', as: "admin" do
		get "/", to: "dashboard#index", as: "root"

		resources :articles, only: [:new, :create, :edit, :update, :destroy]
	end

	resources :articles, only: [:index, :show] do
		resources :comments, only: [:create]
	end
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments, dependent: :destroy

	def render_body
		context = {
			# NOTE this is would clearly not work in production and I don't really
			# know how I would include Emoji's in production
			:asset_root => "http://0.0.0.0:3000/assets",
			:base_url => "http://0.0.0.0:3000"
		}

		pipeline = HTML::Pipeline.new [
			HTML::Pipeline::MarkdownFilter,
			HTML::Pipeline::EmojiFilter
		], context

		pipeline.call(body)[:output].to_s
	end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article

	validates_presence_of :body
end

app/models/dashboard.rb
class Dashboard
	def articles
		Article.all.order("ID DESC")
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
end

app/models/user_settings.rb
class UserSettings < ActiveRecord::Base
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
	before_filter :require_login
	layout 'admin'

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		if params[:publish]
			@article.published = true
		end
		@article.save

		redirect_to admin_root_path
	end

	def edit
		@article = Article.find(params[:id])		
	end

	def update
		@article = Article.find(params[:id])
		if params[:publish]
			@article.published = true
		else
			@article.published = false
		end
		@article.update(article_params)

		redirect_to admin_root_path
	end

	def destroy
		@article = Article.find(params[:id])

		if params[:article][:title] == @article.title
			@article.destroy
			redirect_to admin_root_path
		else
			flash[:notice] = "You must confirm the article's name in order to remove it."
			redirect_to admin_root_path
		end
	end

	private

	def article_params
		params.require(:article).permit(:title, :excerpt, :body)
	end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
	before_filter :require_login
	layout 'admin'

	def index
		@dashboard = Dashboard.new
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all.order("ID DESC")
	end

	def show
		@article = Article.find(params[:id])
	end

	def new
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@article = Article.find(params[:article_id])
		comment = @article.comments.build(comment_params)
		if comment.author.blank?
			comment.author = "Anonymous"
		end
		
		if comment.save
			redirect_to @article
		else
			redirect_to @article, notice: "Comment body is required" 
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:author, :body)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@articles = Article.where('published = true').order("ID DESC")
		@about = UserSettings.first
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Code originally by @yannis_
	# Taken from: http://goo.gl/2AnujD
	def controller?(*controller)
		controller.include?(params[:controller])
	end

	def action?(*action)
		action.include?(params[:action])
	end
end

app/views/admin/articles/_destroy_form.html.erb
<div id="remove_article_confirmation">
<div class="content-subheading"><strong>Danger Zone</strong></div>
	<%= simple_form_for :article, url: admin_article_path(@article), method: :delete do |f| %>
		<span class="warning">Confirm title to delete article:</span>
		<%= f.input :title, label: false, input_html: { value: "" } %>
		<%= f.submit "Remove", class: "pure-button button-warning" %>
	<% end %>
</div>

app/views/admin/articles/_update_form.html.erb
<%= simple_form_for [:admin, @article] do |f| %>
	<%= f.input :title %>
	<%= f.input :excerpt %>
	<%= f.input :body, as: :text, input_html: { rows: 15 } %>
	<%= f.submit "Save as Draft", class: "pure-button pure-button-default" %>
	<%= f.submit "Publish", name: "publish", class: "pure-button button-success" %>
<% end %>

app/views/admin/articles/edit.html.erb
<h1 class="content-subheading">Editing: <%= @article.title %></h1>
<%= render "update_form" %>
<%= render "destroy_form" %>

app/views/admin/articles/new.html.erb
<h1>New Article</h1>
<%= render "update_form" %>

app/views/admin/dashboard/index.html.erb
<h1 class="content-subheading">Articles</h1>
<% @dashboard.articles.each do |article| %>
	<div class="post-listing">
		<div class="post-header">
			<%= "<small>draft</small>".html_safe unless article.published %>
			<h2 class="post-title">
				<%= link_to article.title.titleize, edit_admin_article_path(article) %>
			</h2>
		</div>
		<div class="post-excerpt">
			<p><%= article.excerpt %></p>
		</div>
	</div>
<% end %>

app/views/articles/index.html.erb
<% if @articles.any? %>
	<div class="pure-u-1">
		<div class="content">
			<div class="content-subheading spacer"><strong>Latest Articles</strong></div>
			<% @articles.each do |article| -%>
				<div class="post-listing">
					<div class="post-header">
						<h2 class="post-title"><%= link_to article.title, article %></h2>
						<p class="post-meta">Posted <%= time_ago_in_words(article.created_at) %> ago</p>
					</div>
					<div class="post-excerpt">
						<p><%= article.excerpt %></p>
					</div>
				</div>
			<% end %>
		</div>
	</div>
<% else -%>
	<div class="pure-u-1 pure-u-md-3-5">
		<div class="content">
			<h1>We haven't published anything yet!</h1>
		</div>
	</div>
<% end %>

app/views/articles/show.html.erb
<div class="pure-u-1">
	<div class="post content"> <div class="post-header">
			<h1 class="post-title"><%= @article.title %></h1>
			<p class="post-meta">Posted <%= time_ago_in_words(@article.created_at) %> ago</p>
		</div>
		<div class="post-body">
			<p><%= @article.render_body.html_safe %></p>
		</div>
	</div>
	<div class="comments content">
		<h3 class="content-subheading">Comments</h3>
		<% @article.comments.order("ID DESC").each do |comment| -%>
			<div class="comment">
				<p class="comment-body"><%= comment.body %></p>
				<div class="comment-meta">
					<p>Posted <%= time_ago_in_words(comment.created_at) %> ago by <span class="comment-author"><%= comment.author %></span></p>
				</div>
			</div>
		<% end %>
		<h3 class="content-subheading">Leave a Comment</h3>
		<div class="comment-form">
			<%= simple_form_for [@article, Comment.new] do |f| %>
				<%= f.input :author %>
				<%= f.input :body %>
				<%= f.submit "Post Comment", class: "pure-button pure-button-primary" %>
			<% end %>
		</div>
	</div>

app/views/comments/_comment.html.erb
<%= comment.body %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>SimpleBlog</title>
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
		<!--[if lte IE 8]>
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-old-ie-min.css">
		<![endif]-->
		<!--[if gt IE 8]><!-->
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
		<!--<![endif]-->
		<%= stylesheet_link_tag    'application', media: 'all' %>
		<%= javascript_include_tag 'application' %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div class="admin-topbar pure-g">
			<div class="pure-u-1-2">
				<span class="admin-brand">
					<%= link_to "Dashboard", admin_root_path %>
				</span>
			</div>
			<div class="pure-u-1-2 u-pull-right">
				<% if controller?("admin/articles") && action?("new") %>
				<%= link_to "New Article", "#", id: "new_article_btn", class: "admin-spacer pure-button pure-button-primary pure-button-disabled" %>
			<% else %>
				<%= link_to "New Article", new_admin_article_path, id: "new_article_btn", class: "admin-spacer pure-button pure-button-primary" %>
			<% end %>
				<%= link_to 'Sign out', sign_out_path, method: :delete, class: "pure-button button-warning" %>
			</div>
		</div>

		<div class="pure-g">

			<% flash.each do |key, value| %>
				<div class="flash <%= key %> pure-u-1"><%= value %></div>
			<% end %>

			<div class="content pure-u-1">
				<%= yield %>
			</div>
		</div>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>SimpleBlog</title>
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
		<!--[if lte IE 8]>
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-old-ie-min.css">
		<![endif]-->
		<!--[if gt IE 8]><!-->
		<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
		<!--<![endif]-->
		<%= stylesheet_link_tag    'application', media: 'all' %>
		<%= javascript_include_tag 'application' %>
		<%= csrf_meta_tags %>
	</head>
	<body>


		<div class="pure-g">
			<div class="site-header pure-u-1">
				<div class="site-logo">
					<h1><%= link_to "Simple Blog", root_path %></h1>
				</div>
				<div class="header-nav">
					<ul> 
						<li><a href="#">About</a></li>
						<li><%= link_to "Articles", articles_path %></li>
						<li><a href="#">Something</a></li>
						<li><a href="#">Contact</a></li>
					</ul>
				</div>
			</div>
			<% flash.each do |key, value| %>
				<div class="flash <%= key %> pure-u-1"><%= value %></div>
			<% end %>
		</div>
		<div class="pure-g">
			<%= yield %>
		</div>
	</body>
</html>

app/views/pages/index.html.erb
<div class="pure-u-1 pure-u-sm-2-5">
<div class="bio">
	<div class="content-subheading"><strong>About</strong></div>
	<img class="pure-img about_image" src="http://thenetworkportrait.com/wp-content/uploads/2012/10/IMG_1977-Version-3.jpg">
	<p><%= @about.bio %></p>
</div>
</div>
<% if @articles.any? %>
	<div class="pure-u-1 pure-u-sm-3-5">
		<div class="content">
			<div class="content-subheading spacer"><strong>Latest Articles</strong></div>
			<% @articles.each do |article| -%>
				<div class="post-listing">
					<div class="post-header">
						<h2 class="post-title"><%= link_to article.title, article %></h2>
						<p class="post-meta">Posted <%= time_ago_in_words(article.created_at) %> ago</p>
					</div>
					<div class="post-excerpt">
						<p><%= article.excerpt %></p>
					</div>
				</div>
			<% end %>
		</div>
	</div>
<% else -%>
	<div class="pure-u-1 pure-u-md-3-5">
		<div class="content">
			<h1>We haven't published anything yet!</h1>
		</div>
	</div>
<% end %>